shell.run("wget https://raw.githubusercontent.com/zacharylott94/minelib/master/portable/installation/routeraliases")
shell.run("wget https://raw.githubusercontent.com/zacharylott94/minelib/master/portable/installation/routeratable")
shell.run("wget https://raw.githubusercontent.com/zacharylott94/minelib/master/portable/updater_scripts/updateRouter.lua")
shell.run("wget https://raw.githubusercontent.com/zacharylott94/minelib/master/portable/updater_scripts/updateRouter_dev.lua")
shell.run("updateRouter")